// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarqueeTall from "@/components/sections/hero/HeroSplitVerticalMarqueeTall";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroSplitVerticalMarqueeTall
        textAnimation="fade-blur"
        tag="Ascentra — Digital Growth Agency"
        title="Accelerate Business Growth with Modern Web & AI Solutions"
        description="Ascentra empowers growing businesses with custom Website Creation & Upgrades, 24/7 AI Receptionist Services, and high-converting Meta Advertisements."
        primaryButton={{ text: "Start Project", href: "#contact" }}
        secondaryButton={{ text: "View Work", href: "#work" }}
        leftItems={[
          { imageSrc: "https://storage.googleapis.com/webild/users/user_3JQU3pRqc2xbd0vbgOX0M4axBzx/uploaded-1790025502712-84gn3igk.jpg" },
          { imageSrc: "https://storage.googleapis.com/webild/users/user_3JQU3pRqc2xbd0vbgOX0M4axBzx/uploaded-1790025502713-twynv2i2.jpg" },
          { imageSrc: "https://storage.googleapis.com/webild/users/user_3JQU3pRqc2xbd0vbgOX0M4axBzx/uploaded-1790025502713-qbrd19m7.jpg" },
        ]}
        rightItems={[
          { imageSrc: "https://storage.googleapis.com/webild/users/user_3JQU3pRqc2xbd0vbgOX0M4axBzx/uploaded-1790025502714-1tm0zfu8.jpg" },
          { imageSrc: "https://storage.googleapis.com/webild/users/user_3JQU3pRqc2xbd0vbgOX0M4axBzx/uploaded-1790025502714-vprgm4gi.jpg" },
          { imageSrc: "https://storage.googleapis.com/webild/users/user_3JQU3pRqc2xbd0vbgOX0M4axBzx/uploaded-1790025502712-84gn3igk.jpg" },
        ]}
      />
            </div>
  );
}
