// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarqueeTall from "@/components/sections/hero/HeroSplitVerticalMarqueeTall";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroSplitVerticalMarqueeTall
        textAnimation="fade-blur"
        tag="Ascentra — Digital Growth Agency"
        title="Accelerate Business Growth with Modern Web & AI Solutions"
        description="Ascentra empowers growing businesses with custom Website Creation & Upgrades, 24/7 AI Receptionist Services, and high-converting Meta Advertisements."
        primaryButton={{ text: "Start Project", href: "#contact" }}
        secondaryButton={{ text: "View Work", href: "#work" }}
        leftItems={[
                  { imageSrc: "https://picsum.photos/seed/1604496805/1200/800" },
                  { imageSrc: "https://picsum.photos/seed/750221651/1200/800" },
                  { imageSrc: "https://picsum.photos/seed/131156490/1200/800" },
                  { imageSrc: "https://picsum.photos/seed/1990816992/1200/800" },
                ]}
        rightItems={[
                  { imageSrc: "https://picsum.photos/seed/389081055/1200/800" },
                  { imageSrc: "https://picsum.photos/seed/1195032752/1200/800" },
                  { imageSrc: "https://picsum.photos/seed/423077116/1200/800" },
                  { imageSrc: "https://picsum.photos/seed/1976108597/1200/800" },
                ]}
      />
            </div>
  );
}
