// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBento from "@/components/sections/features/FeaturesBento";
import { Monitor, Zap, Shield, ArrowUpRight, Code, Palette, Layers, PenTool, Sparkles } from "lucide-react";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesBento
        textAnimation="fade-blur"
        tag="Core Offerings"
        title="Services Engineered for Growth"
        description="We deliver high-impact digital solutions engineered to acquire leads and elevate your online presence."
        features={[{"completedLabel":"Live","title":"Website Creation & Upgrade","bentoComponent":"checklist-timeline","description":"High-performing, responsive websites built from scratch or revamped for maximum conversion and speed.","heading":"Delivery Timeline","subheading":"Structured Process"},{"aiIcon":"Bot","placeholder":"AI Receptionist active 24/7...","title":"24/7 AI Receptionist Services","exchanges":[{"aiResponse":"Hello! I can take your reservation or answer any questions about our services right now.","userMessage":"Hi, I'd like to book an appointment for tomorrow."},{"aiResponse":"I've scheduled your consultation and sent a text confirmation. Anything else?","userMessage":"Can you confirm my appointment time?"}],"userIcon":"User","bentoComponent":"chat-marquee"},{"title":"Meta Advertisements","bentoComponent":"animated-bar-chart","description":"Data-driven Meta ad campaigns targeting your ideal audience to turn clicks into loyal customers."}]}
      />
            </div>
  );
}
